// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;
import java_cup.runtime.Symbol;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements  java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\0"+
    "\1\23\1\24\1\25\1\26\2\0\32\27\1\30\1\31"+
    "\1\32\1\0\1\33\1\0\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\27\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\27\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\27\1\61\1\27\1\62\1\63"+
    "\1\64\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\22\24\1\27\1\1\1\30\1\31\1\0\1\32\1\5"+
    "\1\33\1\0\1\2\1\0\1\34\1\35\1\36\1\37"+
    "\25\24\1\40\16\24\1\41\1\0\1\5\1\0\1\2"+
    "\1\0\1\17\1\42\11\24\1\43\4\24\1\44\2\24"+
    "\1\45\5\24\1\46\11\24\1\47\4\24\1\50\2\24"+
    "\1\51\3\24\1\52\1\24\1\53\12\24\1\54\1\24"+
    "\1\55\3\24\1\56\13\24\1\57\1\24\1\60\1\61"+
    "\1\62\1\24\1\63\2\24\1\64\1\24\1\65\5\24"+
    "\1\66\1\67\12\24\1\70\2\24\1\71\1\24\1\72"+
    "\1\73\4\24\1\74\4\24\1\75\1\24\1\76\7\24"+
    "\1\77\1\100\1\101\7\24\1\102\1\103\3\24\1\104"+
    "\1\105\1\106\1\107\6\24\1\110\1\111\1\112\1\113"+
    "\1\24\1\114\1\24\1\115\3\24\1\116\1\117\1\24"+
    "\1\120\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[274];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\65\0\152\0\237\0\324\0\65"+
    "\0\u0109\0\65\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\u013e\0\u0173\0\65\0\u01a8\0\u01dd\0\u0212\0\u0247\0\65"+
    "\0\65\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba"+
    "\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562"+
    "\0\u0597\0\u05cc\0\u0601\0\65\0\u0636\0\65\0\65\0\u066b"+
    "\0\65\0\u06a0\0\65\0\u06d5\0\u070a\0\u073f\0\u0774\0\65"+
    "\0\65\0\65\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2"+
    "\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a"+
    "\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0247"+
    "\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\65\0\u0ee8"+
    "\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u1090"+
    "\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\u0247"+
    "\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u0247\0\u130c\0\u1341\0\u0247"+
    "\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u0247\0\u147f\0\u14b4"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u0247"+
    "\0\u165c\0\u1691\0\u16c6\0\u16fb\0\u0247\0\u1730\0\u1765\0\u0247"+
    "\0\u179a\0\u17cf\0\u1804\0\u0fbc\0\u1839\0\u0247\0\u186e\0\u18a3"+
    "\0\u18d8\0\u190d\0\u1942\0\u1977\0\u19ac\0\u19e1\0\u1a16\0\u1a4b"+
    "\0\u0247\0\u1a80\0\u0247\0\u1ab5\0\u1aea\0\u1b1f\0\u0247\0\u1b54"+
    "\0\u1b89\0\u1bbe\0\u1bf3\0\u1c28\0\u1c5d\0\u1c92\0\u1cc7\0\u1cfc"+
    "\0\u1d31\0\u1d66\0\u0247\0\u1d9b\0\u0247\0\u0247\0\u0247\0\u1dd0"+
    "\0\u0247\0\u1e05\0\u1e3a\0\u0247\0\u1e6f\0\u0247\0\u1ea4\0\u1ed9"+
    "\0\u1f0e\0\u1f43\0\u1f78\0\u0247\0\u0247\0\u1fad\0\u1fe2\0\u2017"+
    "\0\u204c\0\u2081\0\u20b6\0\u20eb\0\u2120\0\u2155\0\u218a\0\u0247"+
    "\0\u21bf\0\u21f4\0\u0247\0\u2229\0\u0247\0\u0247\0\u225e\0\u2293"+
    "\0\u22c8\0\u22fd\0\u0247\0\u2332\0\u2367\0\u239c\0\u23d1\0\u0247"+
    "\0\u2406\0\u0247\0\u243b\0\u2470\0\u24a5\0\u24da\0\u250f\0\u2544"+
    "\0\u2579\0\u0247\0\u0247\0\u0247\0\u25ae\0\u25e3\0\u2618\0\u264d"+
    "\0\u2682\0\u26b7\0\u26ec\0\u0247\0\u0247\0\u2721\0\u2756\0\u278b"+
    "\0\u0247\0\u0247\0\u0247\0\u0247\0\u27c0\0\u27f5\0\u282a\0\u285f"+
    "\0\u2894\0\u28c9\0\u0247\0\u0247\0\u0247\0\u0247\0\u28fe\0\u0247"+
    "\0\u2933\0\u0247\0\u2968\0\u299d\0\u29d2\0\u0247\0\u0247\0\u2a07"+
    "\0\u0247\0\u0247";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[274];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\2\1\31\1\27\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\27\1\41\1\27\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\27\1\52"+
    "\1\53\1\27\1\54\1\55\1\56\67\0\1\4\107\0"+
    "\1\57\37\0\2\7\1\60\2\7\1\60\1\7\1\61"+
    "\21\7\1\62\33\7\11\0\1\63\67\0\1\64\4\0"+
    "\1\65\63\0\1\66\1\0\1\22\4\0\1\67\3\0"+
    "\27\67\30\0\1\70\64\0\1\71\64\0\1\72\61\0"+
    "\1\27\4\0\1\27\3\0\27\27\25\0\1\27\4\0"+
    "\1\27\3\0\3\27\1\73\23\27\25\0\1\27\4\0"+
    "\1\27\3\0\16\27\1\74\1\27\1\75\6\27\25\0"+
    "\1\27\4\0\1\27\3\0\16\27\1\76\4\27\1\77"+
    "\3\27\25\0\1\27\4\0\1\27\3\0\5\27\1\100"+
    "\3\27\1\101\15\27\25\0\1\27\4\0\1\27\3\0"+
    "\15\27\1\102\6\27\1\103\2\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\104\25\27\25\0\1\27\4\0"+
    "\1\27\3\0\16\27\1\105\1\106\7\27\25\0\1\27"+
    "\4\0\1\27\3\0\15\27\1\107\11\27\25\0\1\27"+
    "\4\0\1\27\3\0\16\27\1\110\10\27\25\0\1\27"+
    "\4\0\1\27\3\0\1\27\1\111\3\27\1\112\3\27"+
    "\1\113\4\27\1\114\10\27\25\0\1\27\4\0\1\27"+
    "\3\0\1\27\1\115\21\27\1\116\3\27\25\0\1\27"+
    "\4\0\1\27\3\0\2\27\1\117\12\27\1\120\11\27"+
    "\25\0\1\27\4\0\1\27\3\0\20\27\1\121\6\27"+
    "\25\0\1\27\4\0\1\27\3\0\5\27\1\122\10\27"+
    "\1\123\4\27\1\124\3\27\25\0\1\27\4\0\1\27"+
    "\3\0\1\27\1\125\3\27\1\126\3\27\1\127\5\27"+
    "\1\130\2\27\1\131\4\27\25\0\1\27\4\0\1\27"+
    "\3\0\20\27\1\132\2\27\1\133\3\27\25\0\1\27"+
    "\4\0\1\27\3\0\1\27\1\134\3\27\1\135\21\27"+
    "\25\0\1\27\4\0\1\27\3\0\1\27\1\136\25\27"+
    "\66\0\1\137\1\0\7\60\1\61\21\60\1\140\33\60"+
    "\2\7\1\0\2\141\1\0\1\7\1\60\55\7\14\64"+
    "\1\142\50\64\2\65\1\3\2\65\1\143\57\65\20\0"+
    "\1\144\1\0\1\145\4\0\1\146\3\0\27\146\25\0"+
    "\1\67\4\0\1\67\3\0\27\67\25\0\1\27\4\0"+
    "\1\27\3\0\3\27\1\147\23\27\25\0\1\27\4\0"+
    "\1\27\3\0\16\27\1\150\10\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\151\14\27\1\152\10\27\25\0"+
    "\1\27\4\0\1\27\3\0\15\27\1\153\11\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\154\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\3\27\1\155\15\27\1\156"+
    "\5\27\25\0\1\27\4\0\1\27\3\0\21\27\1\157"+
    "\5\27\25\0\1\27\4\0\1\27\3\0\4\27\1\160"+
    "\15\27\1\161\4\27\25\0\1\27\4\0\1\27\3\0"+
    "\5\27\1\162\21\27\25\0\1\27\4\0\1\27\3\0"+
    "\13\27\1\163\13\27\25\0\1\27\4\0\1\27\3\0"+
    "\22\27\1\164\4\27\25\0\1\27\4\0\1\27\3\0"+
    "\21\27\1\165\5\27\25\0\1\27\4\0\1\27\3\0"+
    "\11\27\1\166\15\27\25\0\1\27\4\0\1\27\3\0"+
    "\16\27\1\167\10\27\25\0\1\27\4\0\1\27\3\0"+
    "\17\27\1\170\7\27\25\0\1\27\4\0\1\27\3\0"+
    "\21\27\1\171\1\172\4\27\25\0\1\27\4\0\1\27"+
    "\3\0\5\27\1\173\21\27\25\0\1\27\4\0\1\27"+
    "\3\0\24\27\1\174\2\27\25\0\1\27\4\0\1\27"+
    "\3\0\24\27\1\175\2\27\25\0\1\27\4\0\1\27"+
    "\3\0\14\27\1\176\12\27\25\0\1\27\4\0\1\27"+
    "\3\0\21\27\1\177\5\27\25\0\1\27\4\0\1\27"+
    "\3\0\16\27\1\200\10\27\25\0\1\27\4\0\1\27"+
    "\3\0\3\27\1\201\3\27\1\202\14\27\1\203\2\27"+
    "\25\0\1\27\4\0\1\27\3\0\23\27\1\204\3\27"+
    "\25\0\1\27\4\0\1\27\3\0\22\27\1\205\4\27"+
    "\25\0\1\27\4\0\1\27\3\0\13\27\1\206\13\27"+
    "\25\0\1\27\4\0\1\27\3\0\15\27\1\207\4\27"+
    "\1\210\4\27\25\0\1\27\4\0\1\27\3\0\7\27"+
    "\1\211\5\27\1\212\11\27\25\0\1\27\4\0\1\27"+
    "\3\0\5\27\1\213\21\27\25\0\1\27\4\0\1\27"+
    "\3\0\16\27\1\214\1\27\1\215\6\27\25\0\1\27"+
    "\4\0\1\27\3\0\23\27\1\216\3\27\25\0\1\27"+
    "\4\0\1\27\3\0\20\27\1\217\6\27\25\0\1\27"+
    "\4\0\1\27\3\0\20\27\1\220\6\27\25\0\1\27"+
    "\4\0\1\27\3\0\10\27\1\221\16\27\25\0\1\27"+
    "\4\0\1\27\3\0\11\27\1\222\14\27\1\223\3\0"+
    "\2\60\4\0\57\60\2\141\1\0\2\141\1\0\1\141"+
    "\1\0\55\141\14\64\1\142\4\64\1\3\43\64\2\0"+
    "\1\3\102\0\1\224\1\0\1\224\62\0\1\144\1\0"+
    "\1\145\71\0\1\146\3\0\27\146\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\225\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\13\27\1\226\13\27\25\0\1\27\4\0"+
    "\1\27\3\0\12\27\1\227\14\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\230\25\27\25\0\1\27\4\0"+
    "\1\27\3\0\21\27\1\231\5\27\25\0\1\27\4\0"+
    "\1\27\3\0\15\27\1\232\11\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\233\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\234\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\235\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\20\27\1\236\6\27\25\0\1\27\4\0"+
    "\1\27\3\0\15\27\1\237\11\27\25\0\1\27\4\0"+
    "\1\27\3\0\21\27\1\240\5\27\25\0\1\27\4\0"+
    "\1\27\3\0\16\27\1\241\10\27\25\0\1\27\4\0"+
    "\1\27\3\0\3\27\1\242\23\27\25\0\1\27\4\0"+
    "\1\27\3\0\17\27\1\243\7\27\25\0\1\27\4\0"+
    "\1\27\3\0\21\27\1\244\5\27\25\0\1\27\4\0"+
    "\1\27\3\0\16\27\1\245\10\27\25\0\1\27\4\0"+
    "\1\27\3\0\15\27\1\246\11\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\247\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\250\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\251\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\7\27\1\252\17\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\253\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\20\27\1\254\6\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\255\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\256\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\257\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\260\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\21\27\1\261\5\27\25\0\1\27\4\0"+
    "\1\27\3\0\23\27\1\262\3\27\25\0\1\27\4\0"+
    "\1\27\3\0\16\27\1\263\10\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\264\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\17\27\1\265\7\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\266\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\15\27\1\267\11\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\270\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\271\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\17\27\1\272\7\27\25\0\1\27\4\0"+
    "\1\27\3\0\13\27\1\273\13\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\274\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\4\27\1\275\22\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\276\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\4\27\1\277\22\27\25\0\1\27\4\0"+
    "\1\27\3\0\13\27\1\300\13\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\301\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\302\25\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\303\25\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\304\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\305\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\306\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\307\25\27\25\0\1\27\4\0"+
    "\1\27\3\0\4\27\1\310\22\27\25\0\1\27\4\0"+
    "\1\27\3\0\22\27\1\311\4\27\25\0\1\27\4\0"+
    "\1\27\3\0\7\27\1\312\17\27\25\0\1\27\4\0"+
    "\1\27\3\0\1\27\1\313\25\27\25\0\1\27\4\0"+
    "\1\27\3\0\20\27\1\314\6\27\25\0\1\27\4\0"+
    "\1\27\3\0\11\27\1\315\15\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\316\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\20\27\1\317\6\27\25\0\1\27\4\0"+
    "\1\27\3\0\5\27\1\320\21\27\25\0\1\27\4\0"+
    "\1\27\3\0\15\27\1\321\11\27\25\0\1\27\4\0"+
    "\1\27\3\0\4\27\1\322\13\27\1\323\6\27\25\0"+
    "\1\27\4\0\1\27\3\0\16\27\1\324\10\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\325\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\4\27\1\326\22\27\25\0"+
    "\1\27\4\0\1\27\3\0\3\27\1\327\23\27\25\0"+
    "\1\27\4\0\1\27\3\0\16\27\1\330\10\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\331\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\3\27\1\332\23\27\25\0"+
    "\1\27\4\0\1\27\3\0\16\27\1\333\10\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\334\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\15\27\1\335\11\27\25\0"+
    "\1\27\4\0\1\27\3\0\15\27\1\336\11\27\25\0"+
    "\1\27\4\0\1\27\3\0\4\27\1\337\22\27\25\0"+
    "\1\27\4\0\1\27\3\0\16\27\1\340\10\27\25\0"+
    "\1\27\4\0\1\27\3\0\7\27\1\341\17\27\25\0"+
    "\1\27\4\0\1\27\3\0\16\27\1\342\10\27\25\0"+
    "\1\27\4\0\1\27\3\0\20\27\1\343\6\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\344\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\3\27\1\345\23\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\346\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\24\27\1\347\2\27\25\0"+
    "\1\27\4\0\1\27\3\0\21\27\1\350\5\27\25\0"+
    "\1\27\4\0\1\27\3\0\21\27\1\351\5\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\352\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\353\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\20\27\1\354\6\27\25\0"+
    "\1\27\4\0\1\27\3\0\13\27\1\355\13\27\25\0"+
    "\1\27\4\0\1\27\3\0\11\27\1\356\15\27\25\0"+
    "\1\27\4\0\1\27\3\0\20\27\1\357\6\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\360\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\20\27\1\361\6\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\362\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\3\27\1\363\23\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\364\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\365\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\366\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\22\27\1\367\4\27\25\0"+
    "\1\27\4\0\1\27\3\0\13\27\1\370\13\27\25\0"+
    "\1\27\4\0\1\27\3\0\14\27\1\371\12\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\372\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\373\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\374\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\375\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\15\27\1\376\11\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\377\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\21\27\1\u0100\5\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\27\1\u0101\25\27\25\0"+
    "\1\27\4\0\1\27\3\0\22\27\1\u0102\4\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\u0103\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\21\27\1\u0104\5\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\u0105\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\5\27\1\u0106\21\27\25\0"+
    "\1\27\4\0\1\27\3\0\1\u0107\26\27\25\0\1\27"+
    "\4\0\1\27\3\0\22\27\1\u0108\4\27\25\0\1\27"+
    "\4\0\1\27\3\0\22\27\1\u0109\4\27\25\0\1\27"+
    "\4\0\1\27\3\0\22\27\1\u010a\4\27\25\0\1\27"+
    "\4\0\1\27\3\0\22\27\1\u010b\4\27\25\0\1\27"+
    "\4\0\1\27\3\0\11\27\1\u010c\15\27\25\0\1\27"+
    "\4\0\1\27\3\0\11\27\1\u010d\15\27\25\0\1\27"+
    "\4\0\1\27\3\0\5\27\1\u010e\21\27\25\0\1\27"+
    "\4\0\1\27\3\0\5\27\1\u010f\21\27\25\0\1\27"+
    "\4\0\1\27\3\0\16\27\1\u0110\10\27\25\0\1\27"+
    "\4\0\1\27\3\0\4\27\1\u0111\22\27\25\0\1\27"+
    "\4\0\1\27\3\0\15\27\1\u0112\11\27\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10812];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\3\1\1\11\1\1\7\11\2\1\1\11"+
    "\4\1\2\11\22\1\1\11\1\1\2\11\1\0\1\11"+
    "\1\1\1\11\1\0\1\1\1\0\1\1\3\11\44\1"+
    "\1\11\1\0\1\1\1\0\1\1\1\0\256\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[274];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public ArrayList<TError> lexerErrors = new ArrayList<>();
    
    // Bandera para controlar el punto y coma
    private boolean seEsperaPuntoYComa = false;

    // Estado de pánico SOLO para faltas de ';': si hay varias líneas seguidas sin ';',
    // reportamos SOLO la falta más baja (la última) cuando encontremos un punto de
    // sincronización (;, }, end o EOF).
    private boolean panicFaltaPuntoYComa = false;
    private int panicSemiLine = 0;
    private int panicSemiColumn = 0;
    private boolean injectingSyntheticSemi = false;

    private void markMissingSemi(int line, int column) {
      panicFaltaPuntoYComa = true;
      panicSemiLine = line + 1;
      panicSemiColumn = column;
    }

    private void flushMissingSemiIfAny() {
      if (panicFaltaPuntoYComa) {
        String msg = "Error Léxico: Falta punto y coma ';' al final de la línea.";
        lexerErrors.add(new TError(panicSemiLine, panicSemiColumn, msg));
        panicFaltaPuntoYComa = false;
      }
    }

    // Cuando estamos en cabeceras que abren bloque (ej: program X {, metodo X(...) {,
    // rutina X(...) {, inicio {, cuando (...) {, mientras (...) {, sino {, loop { )
    // NO queremos exigir ';' al final de línea.
    private boolean enCabeceraBloque = false;

    private Symbol token(String lexeme, String lexicalComp, int line, int column, int symCode) {

      // Si venimos arrastrando faltas de ';', las reportamos solo cuando
      // llegamos a un punto de sincronización.
      if (!injectingSyntheticSemi && (symCode == sym.SEMI || symCode == sym.RBRACE || symCode == sym.END)) {
        flushMissingSemiIfAny();
      }

        // En cabeceras de bloque evitamos exigir ';' en saltos de línea.
        if (enCabeceraBloque) {
            seEsperaPuntoYComa = false;
        } else {
            // Tokens que finalizan una instrucción
            if (symCode == sym.ID || symCode == sym.NUMBER || symCode == sym.STRING || 
                symCode == sym.RPAREN || symCode == sym.RBRACK || 
                symCode == sym.TRUE || symCode == sym.FALSE || 
                symCode == sym.SALIR ||    
                symCode == sym.BRAKE ||    
                symCode == sym.STOP  ||    
                symCode == sym.REGRESA) { 

                seEsperaPuntoYComa = true;
            } else {
                seEsperaPuntoYComa = false;
            }
        }

        Token t = new Token(lexeme, lexicalComp, line + 1, column + 1);
        return new Symbol(symCode, line + 1, column + 1, t);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { flushMissingSemiIfAny(); return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { if (!yytext().trim().isEmpty()) {
        lexerErrors.add(new TError(yyline + 1, yycolumn, "Error Léxico: Caracter inválido '" + yytext() + "'"));
        return token(yytext(), "ERROR", yyline, yycolumn, sym.error);
    }
            }
          // fall through
          case 82: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 83: break;
          case 3:
            { if (seEsperaPuntoYComa) {
          // No dispares el error aquí: acumúlalo y reporta solo el último.
          markMissingSemi(yyline, yycolumn);
          seEsperaPuntoYComa = false; 

        // Inyectar ';' sintético para evitar arrastre en el parser.
        injectingSyntheticSemi = true;
        java_cup.runtime.Symbol s = token(";", "SEMI", yyline, yycolumn, sym.SEMI);
        injectingSyntheticSemi = false;
        return s;
        }
            }
          // fall through
          case 84: break;
          case 4:
            { return token(yytext(), "NOT", yyline, yycolumn, sym.NOT);
            }
          // fall through
          case 85: break;
          case 5:
            { lexerErrors.add(new TError(yyline + 1, yycolumn, "Error Léxico: Comillas sin cerrar."));
    seEsperaPuntoYComa = false; 
    return token(yytext(), "STRING", yyline, yycolumn, sym.STRING);
            }
          // fall through
          case 86: break;
          case 6:
            { return token(yytext(), "MOD", yyline, yycolumn, sym.MOD);
            }
          // fall through
          case 87: break;
          case 7:
            { return token(yytext(), "LPAREN", yyline, yycolumn, sym.LPAREN);
            }
          // fall through
          case 88: break;
          case 8:
            { return token(yytext(), "RPAREN", yyline, yycolumn, sym.RPAREN);
            }
          // fall through
          case 89: break;
          case 9:
            { return token(yytext(), "MUL", yyline, yycolumn, sym.MUL);
            }
          // fall through
          case 90: break;
          case 10:
            { return token(yytext(), "PLUS", yyline, yycolumn, sym.PLUS);
            }
          // fall through
          case 91: break;
          case 11:
            { return token(yytext(), "COMMA", yyline, yycolumn, sym.COMMA);
            }
          // fall through
          case 92: break;
          case 12:
            { return token(yytext(), "MINUS", yyline, yycolumn, sym.MINUS);
            }
          // fall through
          case 93: break;
          case 13:
            { return token(yytext(), "POINT", yyline, yycolumn, sym.error);
            }
          // fall through
          case 94: break;
          case 14:
            { return token(yytext(), "DIV", yyline, yycolumn, sym.DIV);
            }
          // fall through
          case 95: break;
          case 15:
            { return token(yytext(), "NUMBER", yyline, yycolumn, sym.NUMBER);
            }
          // fall through
          case 96: break;
          case 16:
            { return token(yytext(), "SEMI", yyline, yycolumn, sym.SEMI);
            }
          // fall through
          case 97: break;
          case 17:
            { return token(yytext(), "LT", yyline, yycolumn, sym.LT);
            }
          // fall through
          case 98: break;
          case 18:
            { return token(yytext(), "ASSIGN", yyline, yycolumn, sym.ASSIGN);
            }
          // fall through
          case 99: break;
          case 19:
            { return token(yytext(), "GT", yyline, yycolumn, sym.GT);
            }
          // fall through
          case 100: break;
          case 20:
            { return token(yytext(), "ID", yyline, yycolumn, sym.ID);
            }
          // fall through
          case 101: break;
          case 21:
            { return token(yytext(), "LBRACK", yyline, yycolumn, sym.LBRACK);
            }
          // fall through
          case 102: break;
          case 22:
            { return token(yytext(), "RBRACK", yyline, yycolumn, sym.RBRACK);
            }
          // fall through
          case 103: break;
          case 23:
            { seEsperaPuntoYComa = false; enCabeceraBloque = false; return token(yytext(), "LBRACE", yyline, yycolumn, sym.LBRACE);
            }
          // fall through
          case 104: break;
          case 24:
            { seEsperaPuntoYComa = false; return token(yytext(), "RBRACE", yyline, yycolumn, sym.RBRACE);
            }
          // fall through
          case 105: break;
          case 25:
            { return token(yytext(), "NEQ", yyline, yycolumn, sym.NEQ);
            }
          // fall through
          case 106: break;
          case 26:
            { return token(yytext(), "STRING", yyline, yycolumn, sym.STRING);
            }
          // fall through
          case 107: break;
          case 27:
            { return token(yytext(), "AND", yyline, yycolumn, sym.AND);
            }
          // fall through
          case 108: break;
          case 28:
            { lexerErrors.add(new TError(yyline + 1, yycolumn, "Error Léxico: Identificador inválido '" + yytext() + "'. No puede iniciar con número."));
    return token(yytext(), "ERROR", yyline, yycolumn, sym.error);
            }
          // fall through
          case 109: break;
          case 29:
            { return token(yytext(), "LE", yyline, yycolumn, sym.LE);
            }
          // fall through
          case 110: break;
          case 30:
            { return token(yytext(), "EQ", yyline, yycolumn, sym.EQ);
            }
          // fall through
          case 111: break;
          case 31:
            { return token(yytext(), "GE", yyline, yycolumn, sym.GE);
            }
          // fall through
          case 112: break;
          case 32:
            { return token(yytext(), "ON", yyline, yycolumn, sym.ON);
            }
          // fall through
          case 113: break;
          case 33:
            { return token(yytext(), "OR", yyline, yycolumn, sym.OR);
            }
          // fall through
          case 114: break;
          case 34:
            { lexerErrors.add(new TError(yyline + 1, yycolumn, "Error Léxico: Formato de número inválido '" + yytext() + "'."));
    return token(yytext(), "ERROR", yyline, yycolumn, sym.error);
            }
          // fall through
          case 115: break;
          case 35:
            { return token(yytext(), "END", yyline, yycolumn, sym.END);
            }
          // fall through
          case 116: break;
          case 36:
            { return token(yytext(), "GPS", yyline, yycolumn, sym.GPS);
            }
          // fall through
          case 117: break;
          case 37:
            { return token(yytext(), "MAP", yyline, yycolumn, sym.MAP);
            }
          // fall through
          case 118: break;
          case 38:
            { return token(yytext(), "NUM", yyline, yycolumn, sym.NUM);
            }
          // fall through
          case 119: break;
          case 39:
            { return token(yytext(), "SET", yyline, yycolumn, sym.SET);
            }
          // fall through
          case 120: break;
          case 40:
            { return token(yytext(), "STR", yyline, yycolumn, sym.STR);
            }
          // fall through
          case 121: break;
          case 41:
            { return token(yytext(), "VAR", yyline, yycolumn, sym.VAR);
            }
          // fall through
          case 122: break;
          case 42:
            { lexerErrors.add(new TError(yyline + 1, yycolumn, "Error Léxico: Número mal formado '" + yytext() + "'. Demasiados puntos."));
    return token(yytext(), "ERROR", yyline, yycolumn, sym.error);
            }
          // fall through
          case 123: break;
          case 43:
            { return token(yytext(), "BOOL", yyline, yycolumn, sym.BOOL);
            }
          // fall through
          case 124: break;
          case 44:
            { return token(yytext(), "GOTO", yyline, yycolumn, sym.GOTO);
            }
          // fall through
          case 125: break;
          case 45:
            { enCabeceraBloque = true; return token(yytext(), "LOOP", yyline, yycolumn, sym.LOOP);
            }
          // fall through
          case 126: break;
          case 46:
            { return token(yytext(), "MOVE", yyline, yycolumn, sym.MOVE);
            }
          // fall through
          case 127: break;
          case 47:
            { enCabeceraBloque = true; return token(yytext(), "SINO", yyline, yycolumn, sym.SINO);
            }
          // fall through
          case 128: break;
          case 48:
            { return token(yytext(), "STOP", yyline, yycolumn, sym.STOP);
            }
          // fall through
          case 129: break;
          case 49:
            { return token(yytext(), "TRUE", yyline, yycolumn, sym.TRUE);
            }
          // fall through
          case 130: break;
          case 50:
            { return token(yytext(), "TURN", yyline, yycolumn, sym.TURN);
            }
          // fall through
          case 131: break;
          case 51:
            { return token(yytext(), "WAIT", yyline, yycolumn, sym.WAIT);
            }
          // fall through
          case 132: break;
          case 52:
            { return token(yytext(), "BRAKE", yyline, yycolumn, sym.BRAKE);
            }
          // fall through
          case 133: break;
          case 53:
            { return token(yytext(), "CONST", yyline, yycolumn, sym.CONST);
            }
          // fall through
          case 134: break;
          case 54:
            { return token(yytext(), "EVENT", yyline, yycolumn, sym.EVENT);
            }
          // fall through
          case 135: break;
          case 55:
            { return token(yytext(), "FALSE", yyline, yycolumn, sym.FALSE);
            }
          // fall through
          case 136: break;
          case 56:
            { return token(yytext(), "ROUTE", yyline, yycolumn, sym.ROUTE);
            }
          // fall through
          case 137: break;
          case 57:
            { return token(yytext(), "SALIR", yyline, yycolumn, sym.SALIR);
            }
          // fall through
          case 138: break;
          case 58:
            { return token(yytext(), "SIGUE", yyline, yycolumn, sym.SIGUE);
            }
          // fall through
          case 139: break;
          case 59:
            { return token(yytext(), "SPEED", yyline, yycolumn, sym.SPEED);
            }
          // fall through
          case 140: break;
          case 60:
            { enCabeceraBloque = true; return token(yytext(), "CUANDO", yyline, yycolumn, sym.CUANDO);
            }
          // fall through
          case 141: break;
          case 61:
            { enCabeceraBloque = true; return token(yytext(), "INICIO", yyline, yycolumn, sym.INICIO);
            }
          // fall through
          case 142: break;
          case 62:
            { enCabeceraBloque = true; return token(yytext(), "METODO", yyline, yycolumn, sym.METODO);
            }
          // fall through
          case 143: break;
          case 63:
            { enCabeceraBloque = true; return token(yytext(), "RUTINA", yyline, yycolumn, sym.RUTINA);
            }
          // fall through
          case 144: break;
          case 64:
            { return token(yytext(), "SALIDA", yyline, yycolumn, sym.SALIDA);
            }
          // fall through
          case 145: break;
          case 65:
            { return token(yytext(), "SENSOR", yyline, yycolumn, sym.SENSOR);
            }
          // fall through
          case 146: break;
          case 66:
            { return token(yytext(), "ENTRADA", yyline, yycolumn, sym.ENTRADA);
            }
          // fall through
          case 147: break;
          case 67:
            { return token(yytext(), "MESSAGE", yyline, yycolumn, sym.MESSAGE);
            }
          // fall through
          case 148: break;
          case 68:
            { enCabeceraBloque = true; return token(yytext(), "PROGRAM", yyline, yycolumn, sym.PROGRAM);
            }
          // fall through
          case 149: break;
          case 69:
            { return token(yytext(), "RECEIVE", yyline, yycolumn, sym.RECEIVE);
            }
          // fall through
          case 150: break;
          case 70:
            { return token(yytext(), "REGRESA", yyline, yycolumn, sym.REGRESA);
            }
          // fall through
          case 151: break;
          case 71:
            { return token(yytext(), "REVERSE", yyline, yycolumn, sym.REVERSE);
            }
          // fall through
          case 152: break;
          case 72:
            { return token(yytext(), "DISTANCE", yyline, yycolumn, sym.DISTANCE);
            }
          // fall through
          case 153: break;
          case 73:
            { enCabeceraBloque = true; return token(yytext(), "MIENTRAS", yyline, yycolumn, sym.MIENTRAS);
            }
          // fall through
          case 154: break;
          case 74:
            { return token(yytext(), "NAVIGATE", yyline, yycolumn, sym.NAVIGATE);
            }
          // fall through
          case 155: break;
          case 75:
            { return token(yytext(), "OBSTACLE", yyline, yycolumn, sym.OBSTACLE);
            }
          // fall through
          case 156: break;
          case 76:
            { return token(yytext(), "WAYPOINT", yyline, yycolumn, sym.WAYPOINT);
            }
          // fall through
          case 157: break;
          case 77:
            { return token(yytext(), "BROADCAST", yyline, yycolumn, sym.BROADCAST);
            }
          // fall through
          case 158: break;
          case 78:
            { return token(yytext(), "ACCEL", yyline, yycolumn, sym.ACCEL);
            }
          // fall through
          case 159: break;
          case 79:
            { return token(yytext(), "DECEL", yyline, yycolumn, sym.DECEL);
            }
          // fall through
          case 160: break;
          case 80:
            { return token(yytext(), "VEHICLE_ID", yyline, yycolumn, sym.VEHICLE_ID);
            }
          // fall through
          case 161: break;
          case 81:
            { return token(yytext(), "DESTINATION", yyline, yycolumn, sym.DESTINATION);
            }
          // fall through
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
