// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;
import java_cup.runtime.Symbol;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\0"+
    "\1\23\1\24\1\25\1\26\2\0\32\27\1\30\1\31"+
    "\1\32\1\0\1\33\1\0\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\27\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\27\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\27\1\61\1\27\1\62\1\63"+
    "\1\64\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\22\21\1\24"+
    "\1\1\1\25\1\26\1\0\1\27\1\0\1\30\1\0"+
    "\1\2\1\0\1\31\1\32\1\33\25\21\1\34\16\21"+
    "\1\35\1\0\1\14\11\21\1\36\4\21\1\37\2\21"+
    "\1\40\5\21\1\41\11\21\1\42\4\21\1\43\2\21"+
    "\1\44\4\21\1\45\12\21\1\46\1\21\1\47\3\21"+
    "\1\50\13\21\1\51\1\21\1\52\1\53\1\54\1\21"+
    "\1\55\2\21\1\56\1\21\1\57\5\21\1\60\1\61"+
    "\12\21\1\62\2\21\1\63\1\21\1\64\1\65\4\21"+
    "\1\66\4\21\1\67\1\21\1\70\7\21\1\71\1\72"+
    "\1\73\7\21\1\74\1\75\3\21\1\76\1\77\1\100"+
    "\1\101\6\21\1\102\1\103\1\104\1\105\1\21\1\106"+
    "\1\21\1\107\3\21\1\110\1\111\1\21\1\112\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[265];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\237\0\324\0\65\0\u0109"+
    "\0\65\0\65\0\65\0\65\0\65\0\65\0\u013e\0\u0173"+
    "\0\65\0\u01a8\0\u01dd\0\u0212\0\u0247\0\65\0\65\0\u027c"+
    "\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424"+
    "\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc"+
    "\0\u0601\0\65\0\u0636\0\65\0\65\0\324\0\65\0\u066b"+
    "\0\65\0\u06a0\0\u06d5\0\u070a\0\65\0\65\0\65\0\u073f"+
    "\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7"+
    "\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0247\0\u0b98\0\u0bcd\0\u0c02"+
    "\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa"+
    "\0\u0ddf\0\u0e14\0\u0e49\0\65\0\u0e7e\0\u070a\0\u0eb3\0\u0ee8"+
    "\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u0247"+
    "\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u0247\0\u1164\0\u1199\0\u0247"+
    "\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u0247\0\u12d7\0\u130c"+
    "\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u147f\0\u0247"+
    "\0\u14b4\0\u14e9\0\u151e\0\u1553\0\u0247\0\u1588\0\u15bd\0\u0247"+
    "\0\u15f2\0\u1627\0\u165c\0\u1691\0\u0247\0\u16c6\0\u16fb\0\u1730"+
    "\0\u1765\0\u179a\0\u17cf\0\u1804\0\u1839\0\u186e\0\u18a3\0\u0247"+
    "\0\u18d8\0\u0247\0\u190d\0\u1942\0\u1977\0\u0247\0\u19ac\0\u19e1"+
    "\0\u1a16\0\u1a4b\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f\0\u1b54\0\u1b89"+
    "\0\u1bbe\0\u0247\0\u1bf3\0\u0247\0\u0247\0\u0247\0\u1c28\0\u0247"+
    "\0\u1c5d\0\u1c92\0\u0247\0\u1cc7\0\u0247\0\u1cfc\0\u1d31\0\u1d66"+
    "\0\u1d9b\0\u1dd0\0\u0247\0\u0247\0\u1e05\0\u1e3a\0\u1e6f\0\u1ea4"+
    "\0\u1ed9\0\u1f0e\0\u1f43\0\u1f78\0\u1fad\0\u1fe2\0\u0247\0\u2017"+
    "\0\u204c\0\u0247\0\u2081\0\u0247\0\u0247\0\u20b6\0\u20eb\0\u2120"+
    "\0\u2155\0\u0247\0\u218a\0\u21bf\0\u21f4\0\u2229\0\u0247\0\u225e"+
    "\0\u0247\0\u2293\0\u22c8\0\u22fd\0\u2332\0\u2367\0\u239c\0\u23d1"+
    "\0\u0247\0\u0247\0\u0247\0\u2406\0\u243b\0\u2470\0\u24a5\0\u24da"+
    "\0\u250f\0\u2544\0\u0247\0\u0247\0\u2579\0\u25ae\0\u25e3\0\u0247"+
    "\0\u0247\0\u0247\0\u0247\0\u2618\0\u264d\0\u2682\0\u26b7\0\u26ec"+
    "\0\u2721\0\u0247\0\u0247\0\u0247\0\u0247\0\u2756\0\u0247\0\u278b"+
    "\0\u0247\0\u27c0\0\u27f5\0\u282a\0\u0247\0\u0247\0\u285f\0\u0247"+
    "\0\u0247";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[265];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\2\1\27\1\25\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\25\1\37\1\25\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\25\1\50\1\51"+
    "\1\25\1\52\1\53\1\54\67\0\1\3\107\0\1\55"+
    "\37\0\7\56\1\57\21\56\1\60\33\56\11\0\1\61"+
    "\67\0\1\62\4\0\1\63\63\0\1\64\1\0\1\20"+
    "\67\0\1\65\64\0\1\66\64\0\1\67\61\0\1\25"+
    "\4\0\1\25\3\0\27\25\25\0\1\25\4\0\1\25"+
    "\3\0\3\25\1\70\23\25\25\0\1\25\4\0\1\25"+
    "\3\0\16\25\1\71\1\25\1\72\6\25\25\0\1\25"+
    "\4\0\1\25\3\0\16\25\1\73\4\25\1\74\3\25"+
    "\25\0\1\25\4\0\1\25\3\0\5\25\1\75\3\25"+
    "\1\76\15\25\25\0\1\25\4\0\1\25\3\0\15\25"+
    "\1\77\6\25\1\100\2\25\25\0\1\25\4\0\1\25"+
    "\3\0\1\25\1\101\25\25\25\0\1\25\4\0\1\25"+
    "\3\0\16\25\1\102\1\103\7\25\25\0\1\25\4\0"+
    "\1\25\3\0\15\25\1\104\11\25\25\0\1\25\4\0"+
    "\1\25\3\0\16\25\1\105\10\25\25\0\1\25\4\0"+
    "\1\25\3\0\1\25\1\106\3\25\1\107\3\25\1\110"+
    "\4\25\1\111\10\25\25\0\1\25\4\0\1\25\3\0"+
    "\1\25\1\112\21\25\1\113\3\25\25\0\1\25\4\0"+
    "\1\25\3\0\2\25\1\114\12\25\1\115\11\25\25\0"+
    "\1\25\4\0\1\25\3\0\20\25\1\116\6\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\117\10\25\1\120"+
    "\4\25\1\121\3\25\25\0\1\25\4\0\1\25\3\0"+
    "\1\25\1\122\3\25\1\123\3\25\1\124\5\25\1\125"+
    "\2\25\1\126\4\25\25\0\1\25\4\0\1\25\3\0"+
    "\20\25\1\127\2\25\1\130\3\25\25\0\1\25\4\0"+
    "\1\25\3\0\1\25\1\131\3\25\1\132\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\133\25\25\66\0"+
    "\1\134\1\0\2\56\4\0\57\56\14\62\1\135\50\62"+
    "\2\63\1\3\2\63\1\4\57\63\22\0\1\136\64\0"+
    "\1\25\4\0\1\25\3\0\3\25\1\137\23\25\25\0"+
    "\1\25\4\0\1\25\3\0\16\25\1\140\10\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\141\14\25\1\142"+
    "\10\25\25\0\1\25\4\0\1\25\3\0\15\25\1\143"+
    "\11\25\25\0\1\25\4\0\1\25\3\0\1\25\1\144"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\3\25\1\145"+
    "\15\25\1\146\5\25\25\0\1\25\4\0\1\25\3\0"+
    "\21\25\1\147\5\25\25\0\1\25\4\0\1\25\3\0"+
    "\4\25\1\150\15\25\1\151\4\25\25\0\1\25\4\0"+
    "\1\25\3\0\5\25\1\152\21\25\25\0\1\25\4\0"+
    "\1\25\3\0\13\25\1\153\13\25\25\0\1\25\4\0"+
    "\1\25\3\0\22\25\1\154\4\25\25\0\1\25\4\0"+
    "\1\25\3\0\21\25\1\155\5\25\25\0\1\25\4\0"+
    "\1\25\3\0\11\25\1\156\15\25\25\0\1\25\4\0"+
    "\1\25\3\0\16\25\1\157\10\25\25\0\1\25\4\0"+
    "\1\25\3\0\17\25\1\160\7\25\25\0\1\25\4\0"+
    "\1\25\3\0\21\25\1\161\1\162\4\25\25\0\1\25"+
    "\4\0\1\25\3\0\5\25\1\163\21\25\25\0\1\25"+
    "\4\0\1\25\3\0\24\25\1\164\2\25\25\0\1\25"+
    "\4\0\1\25\3\0\24\25\1\165\2\25\25\0\1\25"+
    "\4\0\1\25\3\0\14\25\1\166\12\25\25\0\1\25"+
    "\4\0\1\25\3\0\21\25\1\167\5\25\25\0\1\25"+
    "\4\0\1\25\3\0\16\25\1\170\10\25\25\0\1\25"+
    "\4\0\1\25\3\0\3\25\1\171\3\25\1\172\14\25"+
    "\1\173\2\25\25\0\1\25\4\0\1\25\3\0\23\25"+
    "\1\174\3\25\25\0\1\25\4\0\1\25\3\0\22\25"+
    "\1\175\4\25\25\0\1\25\4\0\1\25\3\0\13\25"+
    "\1\176\13\25\25\0\1\25\4\0\1\25\3\0\15\25"+
    "\1\177\4\25\1\200\4\25\25\0\1\25\4\0\1\25"+
    "\3\0\7\25\1\201\5\25\1\202\11\25\25\0\1\25"+
    "\4\0\1\25\3\0\5\25\1\203\21\25\25\0\1\25"+
    "\4\0\1\25\3\0\16\25\1\204\1\25\1\205\6\25"+
    "\25\0\1\25\4\0\1\25\3\0\23\25\1\206\3\25"+
    "\25\0\1\25\4\0\1\25\3\0\20\25\1\207\6\25"+
    "\25\0\1\25\4\0\1\25\3\0\20\25\1\210\6\25"+
    "\25\0\1\25\4\0\1\25\3\0\10\25\1\211\16\25"+
    "\25\0\1\25\4\0\1\25\3\0\11\25\1\212\14\25"+
    "\1\213\3\0\14\62\1\135\4\62\1\3\43\62\22\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\214\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\13\25\1\215\13\25\25\0"+
    "\1\25\4\0\1\25\3\0\12\25\1\216\14\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\217\25\25\25\0"+
    "\1\25\4\0\1\25\3\0\21\25\1\220\5\25\25\0"+
    "\1\25\4\0\1\25\3\0\15\25\1\221\11\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\222\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\223\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\224\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\20\25\1\225\6\25\25\0"+
    "\1\25\4\0\1\25\3\0\15\25\1\226\11\25\25\0"+
    "\1\25\4\0\1\25\3\0\21\25\1\227\5\25\25\0"+
    "\1\25\4\0\1\25\3\0\16\25\1\230\10\25\25\0"+
    "\1\25\4\0\1\25\3\0\3\25\1\231\23\25\25\0"+
    "\1\25\4\0\1\25\3\0\17\25\1\232\7\25\25\0"+
    "\1\25\4\0\1\25\3\0\21\25\1\233\5\25\25\0"+
    "\1\25\4\0\1\25\3\0\16\25\1\234\10\25\25\0"+
    "\1\25\4\0\1\25\3\0\15\25\1\235\11\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\236\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\237\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\240\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\7\25\1\241\17\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\242\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\20\25\1\243\6\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\244\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\245\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\246\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\247\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\21\25\1\250\5\25\25\0"+
    "\1\25\4\0\1\25\3\0\23\25\1\251\3\25\25\0"+
    "\1\25\4\0\1\25\3\0\16\25\1\252\10\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\253\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\17\25\1\254\7\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\255\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\15\25\1\256\11\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\257\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\260\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\17\25\1\261\7\25\25\0"+
    "\1\25\4\0\1\25\3\0\13\25\1\262\13\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\263\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\4\25\1\264\22\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\265\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\4\25\1\266\22\25\25\0"+
    "\1\25\4\0\1\25\3\0\13\25\1\267\13\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\270\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\271\25\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\272\25\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\273\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\274\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\275\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\276\25\25\25\0"+
    "\1\25\4\0\1\25\3\0\4\25\1\277\22\25\25\0"+
    "\1\25\4\0\1\25\3\0\22\25\1\300\4\25\25\0"+
    "\1\25\4\0\1\25\3\0\7\25\1\301\17\25\25\0"+
    "\1\25\4\0\1\25\3\0\1\25\1\302\25\25\25\0"+
    "\1\25\4\0\1\25\3\0\20\25\1\303\6\25\25\0"+
    "\1\25\4\0\1\25\3\0\11\25\1\304\15\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\305\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\20\25\1\306\6\25\25\0"+
    "\1\25\4\0\1\25\3\0\5\25\1\307\21\25\25\0"+
    "\1\25\4\0\1\25\3\0\15\25\1\310\11\25\25\0"+
    "\1\25\4\0\1\25\3\0\4\25\1\311\13\25\1\312"+
    "\6\25\25\0\1\25\4\0\1\25\3\0\16\25\1\313"+
    "\10\25\25\0\1\25\4\0\1\25\3\0\5\25\1\314"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\4\25\1\315"+
    "\22\25\25\0\1\25\4\0\1\25\3\0\3\25\1\316"+
    "\23\25\25\0\1\25\4\0\1\25\3\0\16\25\1\317"+
    "\10\25\25\0\1\25\4\0\1\25\3\0\5\25\1\320"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\3\25\1\321"+
    "\23\25\25\0\1\25\4\0\1\25\3\0\16\25\1\322"+
    "\10\25\25\0\1\25\4\0\1\25\3\0\5\25\1\323"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\15\25\1\324"+
    "\11\25\25\0\1\25\4\0\1\25\3\0\15\25\1\325"+
    "\11\25\25\0\1\25\4\0\1\25\3\0\4\25\1\326"+
    "\22\25\25\0\1\25\4\0\1\25\3\0\16\25\1\327"+
    "\10\25\25\0\1\25\4\0\1\25\3\0\7\25\1\330"+
    "\17\25\25\0\1\25\4\0\1\25\3\0\16\25\1\331"+
    "\10\25\25\0\1\25\4\0\1\25\3\0\20\25\1\332"+
    "\6\25\25\0\1\25\4\0\1\25\3\0\1\25\1\333"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\3\25\1\334"+
    "\23\25\25\0\1\25\4\0\1\25\3\0\1\25\1\335"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\24\25\1\336"+
    "\2\25\25\0\1\25\4\0\1\25\3\0\21\25\1\337"+
    "\5\25\25\0\1\25\4\0\1\25\3\0\21\25\1\340"+
    "\5\25\25\0\1\25\4\0\1\25\3\0\1\25\1\341"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\1\25\1\342"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\20\25\1\343"+
    "\6\25\25\0\1\25\4\0\1\25\3\0\13\25\1\344"+
    "\13\25\25\0\1\25\4\0\1\25\3\0\11\25\1\345"+
    "\15\25\25\0\1\25\4\0\1\25\3\0\20\25\1\346"+
    "\6\25\25\0\1\25\4\0\1\25\3\0\1\25\1\347"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\20\25\1\350"+
    "\6\25\25\0\1\25\4\0\1\25\3\0\1\25\1\351"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\3\25\1\352"+
    "\23\25\25\0\1\25\4\0\1\25\3\0\1\25\1\353"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\5\25\1\354"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\1\25\1\355"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\22\25\1\356"+
    "\4\25\25\0\1\25\4\0\1\25\3\0\13\25\1\357"+
    "\13\25\25\0\1\25\4\0\1\25\3\0\14\25\1\360"+
    "\12\25\25\0\1\25\4\0\1\25\3\0\5\25\1\361"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\1\25\1\362"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\5\25\1\363"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\5\25\1\364"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\15\25\1\365"+
    "\11\25\25\0\1\25\4\0\1\25\3\0\1\25\1\366"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\21\25\1\367"+
    "\5\25\25\0\1\25\4\0\1\25\3\0\1\25\1\370"+
    "\25\25\25\0\1\25\4\0\1\25\3\0\22\25\1\371"+
    "\4\25\25\0\1\25\4\0\1\25\3\0\5\25\1\372"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\21\25\1\373"+
    "\5\25\25\0\1\25\4\0\1\25\3\0\5\25\1\374"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\5\25\1\375"+
    "\21\25\25\0\1\25\4\0\1\25\3\0\1\376\26\25"+
    "\25\0\1\25\4\0\1\25\3\0\22\25\1\377\4\25"+
    "\25\0\1\25\4\0\1\25\3\0\22\25\1\u0100\4\25"+
    "\25\0\1\25\4\0\1\25\3\0\22\25\1\u0101\4\25"+
    "\25\0\1\25\4\0\1\25\3\0\22\25\1\u0102\4\25"+
    "\25\0\1\25\4\0\1\25\3\0\11\25\1\u0103\15\25"+
    "\25\0\1\25\4\0\1\25\3\0\11\25\1\u0104\15\25"+
    "\25\0\1\25\4\0\1\25\3\0\5\25\1\u0105\21\25"+
    "\25\0\1\25\4\0\1\25\3\0\5\25\1\u0106\21\25"+
    "\25\0\1\25\4\0\1\25\3\0\16\25\1\u0107\10\25"+
    "\25\0\1\25\4\0\1\25\3\0\4\25\1\u0108\22\25"+
    "\25\0\1\25\4\0\1\25\3\0\15\25\1\u0109\11\25"+
    "\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10388];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\1\1\6\11\2\1\1\11"+
    "\4\1\2\11\22\1\1\11\1\1\2\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\1\1\0\3\11\44\1\1\11"+
    "\1\0\254\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[265];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public ArrayList<TError> lexerErrors = new ArrayList<>();

    private Symbol token(String lexeme, String lexicalComp, int line, int column, int symCode) {
        Token t = new Token(lexeme, lexicalComp, line + 1, column + 1);
        return new Symbol(symCode, line + 1, column + 1, t);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return new java_cup.runtime.Symbol(sym.EOF, yyline+1, yycolumn+1);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { // Guardamos el error en la lista antes de devolver el token
    lexerErrors.add(new TError(yyline+1, yycolumn+1, "Error Léxico: Caracter inválido '" + yytext() + "'"));
    return token(yytext(), "ERROR", yyline, yycolumn, sym.ERROR);
            }
          // fall through
          case 76: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 77: break;
          case 3:
            { return token(yytext(), "NOT", yyline, yycolumn, sym.NOT);
            }
          // fall through
          case 78: break;
          case 4:
            { return token(yytext(), "MOD", yyline, yycolumn, sym.MOD);
            }
          // fall through
          case 79: break;
          case 5:
            { return token(yytext(), "LPAREN", yyline, yycolumn, sym.LPAREN);
            }
          // fall through
          case 80: break;
          case 6:
            { return token(yytext(), "RPAREN", yyline, yycolumn, sym.RPAREN);
            }
          // fall through
          case 81: break;
          case 7:
            { return token(yytext(), "MUL", yyline, yycolumn, sym.MUL);
            }
          // fall through
          case 82: break;
          case 8:
            { return token(yytext(), "PLUS", yyline, yycolumn, sym.PLUS);
            }
          // fall through
          case 83: break;
          case 9:
            { return token(yytext(), "COMMA", yyline, yycolumn, sym.COMMA);
            }
          // fall through
          case 84: break;
          case 10:
            { return token(yytext(), "MINUS", yyline, yycolumn, sym.MINUS);
            }
          // fall through
          case 85: break;
          case 11:
            { return token(yytext(), "DIV", yyline, yycolumn, sym.DIV);
            }
          // fall through
          case 86: break;
          case 12:
            { return token(yytext(), "NUMBER", yyline, yycolumn, sym.NUMBER);
            }
          // fall through
          case 87: break;
          case 13:
            { return token(yytext(), "SEMI", yyline, yycolumn, sym.SEMI);
            }
          // fall through
          case 88: break;
          case 14:
            { return token(yytext(), "LT", yyline, yycolumn, sym.LT);
            }
          // fall through
          case 89: break;
          case 15:
            { return token(yytext(), "ASSIGN", yyline, yycolumn, sym.ASSIGN);
            }
          // fall through
          case 90: break;
          case 16:
            { return token(yytext(), "GT", yyline, yycolumn, sym.GT);
            }
          // fall through
          case 91: break;
          case 17:
            { return token(yytext(), "ID", yyline, yycolumn, sym.ID);
            }
          // fall through
          case 92: break;
          case 18:
            { return token(yytext(), "LBRACK", yyline, yycolumn, sym.LBRACK);
            }
          // fall through
          case 93: break;
          case 19:
            { return token(yytext(), "RBRACK", yyline, yycolumn, sym.RBRACK);
            }
          // fall through
          case 94: break;
          case 20:
            { return token(yytext(), "LBRACE", yyline, yycolumn, sym.LBRACE);
            }
          // fall through
          case 95: break;
          case 21:
            { return token(yytext(), "RBRACE", yyline, yycolumn, sym.RBRACE);
            }
          // fall through
          case 96: break;
          case 22:
            { return token(yytext(), "NEQ", yyline, yycolumn, sym.NEQ);
            }
          // fall through
          case 97: break;
          case 23:
            { return token(yytext(), "STRING", yyline, yycolumn, sym.STRING);
            }
          // fall through
          case 98: break;
          case 24:
            { return token(yytext(), "AND", yyline, yycolumn, sym.AND);
            }
          // fall through
          case 99: break;
          case 25:
            { return token(yytext(), "LE", yyline, yycolumn, sym.LE);
            }
          // fall through
          case 100: break;
          case 26:
            { return token(yytext(), "EQ", yyline, yycolumn, sym.EQ);
            }
          // fall through
          case 101: break;
          case 27:
            { return token(yytext(), "GE", yyline, yycolumn, sym.GE);
            }
          // fall through
          case 102: break;
          case 28:
            { return token(yytext(), "ON", yyline, yycolumn, sym.ON);
            }
          // fall through
          case 103: break;
          case 29:
            { return token(yytext(), "OR", yyline, yycolumn, sym.OR);
            }
          // fall through
          case 104: break;
          case 30:
            { return token(yytext(), "END", yyline, yycolumn, sym.END);
            }
          // fall through
          case 105: break;
          case 31:
            { return token(yytext(), "GPS", yyline, yycolumn, sym.GPS);
            }
          // fall through
          case 106: break;
          case 32:
            { return token(yytext(), "MAP", yyline, yycolumn, sym.MAP);
            }
          // fall through
          case 107: break;
          case 33:
            { return token(yytext(), "NUM", yyline, yycolumn, sym.NUM);
            }
          // fall through
          case 108: break;
          case 34:
            { return token(yytext(), "SET", yyline, yycolumn, sym.SET);
            }
          // fall through
          case 109: break;
          case 35:
            { return token(yytext(), "STR", yyline, yycolumn, sym.STR);
            }
          // fall through
          case 110: break;
          case 36:
            { return token(yytext(), "VAR", yyline, yycolumn, sym.VAR);
            }
          // fall through
          case 111: break;
          case 37:
            { return token(yytext(), "BOOL", yyline, yycolumn, sym.BOOL);
            }
          // fall through
          case 112: break;
          case 38:
            { return token(yytext(), "GOTO", yyline, yycolumn, sym.GOTO);
            }
          // fall through
          case 113: break;
          case 39:
            { return token(yytext(), "LOOP", yyline, yycolumn, sym.LOOP);
            }
          // fall through
          case 114: break;
          case 40:
            { return token(yytext(), "MOVE", yyline, yycolumn, sym.MOVE);
            }
          // fall through
          case 115: break;
          case 41:
            { return token(yytext(), "SINO", yyline, yycolumn, sym.SINO);
            }
          // fall through
          case 116: break;
          case 42:
            { return token(yytext(), "STOP", yyline, yycolumn, sym.STOP);
            }
          // fall through
          case 117: break;
          case 43:
            { return token(yytext(), "TRUE", yyline, yycolumn, sym.TRUE);
            }
          // fall through
          case 118: break;
          case 44:
            { return token(yytext(), "TURN", yyline, yycolumn, sym.TURN);
            }
          // fall through
          case 119: break;
          case 45:
            { return token(yytext(), "WAIT", yyline, yycolumn, sym.WAIT);
            }
          // fall through
          case 120: break;
          case 46:
            { return token(yytext(), "BRAKE", yyline, yycolumn, sym.BRAKE);
            }
          // fall through
          case 121: break;
          case 47:
            { return token(yytext(), "CONST", yyline, yycolumn, sym.CONST);
            }
          // fall through
          case 122: break;
          case 48:
            { return token(yytext(), "EVENT", yyline, yycolumn, sym.EVENT);
            }
          // fall through
          case 123: break;
          case 49:
            { return token(yytext(), "FALSE", yyline, yycolumn, sym.FALSE);
            }
          // fall through
          case 124: break;
          case 50:
            { return token(yytext(), "ROUTE", yyline, yycolumn, sym.ROUTE);
            }
          // fall through
          case 125: break;
          case 51:
            { return token(yytext(), "SALIR", yyline, yycolumn, sym.SALIR);
            }
          // fall through
          case 126: break;
          case 52:
            { return token(yytext(), "SIGUE", yyline, yycolumn, sym.SIGUE);
            }
          // fall through
          case 127: break;
          case 53:
            { return token(yytext(), "SPEED", yyline, yycolumn, sym.SPEED);
            }
          // fall through
          case 128: break;
          case 54:
            { return token(yytext(), "CUANDO", yyline, yycolumn, sym.CUANDO);
            }
          // fall through
          case 129: break;
          case 55:
            { return token(yytext(), "INICIO", yyline, yycolumn, sym.INICIO);
            }
          // fall through
          case 130: break;
          case 56:
            { return token(yytext(), "METODO", yyline, yycolumn, sym.METODO);
            }
          // fall through
          case 131: break;
          case 57:
            { return token(yytext(), "RUTINA", yyline, yycolumn, sym.RUTINA);
            }
          // fall through
          case 132: break;
          case 58:
            { return token(yytext(), "SALIDA", yyline, yycolumn, sym.SALIDA);
            }
          // fall through
          case 133: break;
          case 59:
            { return token(yytext(), "SENSOR", yyline, yycolumn, sym.SENSOR);
            }
          // fall through
          case 134: break;
          case 60:
            { return token(yytext(), "ENTRADA", yyline, yycolumn, sym.ENTRADA);
            }
          // fall through
          case 135: break;
          case 61:
            { return token(yytext(), "MESSAGE", yyline, yycolumn, sym.MESSAGE);
            }
          // fall through
          case 136: break;
          case 62:
            { return token(yytext(), "PROGRAM", yyline, yycolumn, sym.PROGRAM);
            }
          // fall through
          case 137: break;
          case 63:
            { return token(yytext(), "RECEIVE", yyline, yycolumn, sym.RECEIVE);
            }
          // fall through
          case 138: break;
          case 64:
            { return token(yytext(), "REGRESA", yyline, yycolumn, sym.REGRESA);
            }
          // fall through
          case 139: break;
          case 65:
            { return token(yytext(), "REVERSE", yyline, yycolumn, sym.REVERSE);
            }
          // fall through
          case 140: break;
          case 66:
            { return token(yytext(), "DISTANCE", yyline, yycolumn, sym.DISTANCE);
            }
          // fall through
          case 141: break;
          case 67:
            { return token(yytext(), "MIENTRAS", yyline, yycolumn, sym.MIENTRAS);
            }
          // fall through
          case 142: break;
          case 68:
            { return token(yytext(), "NAVIGATE", yyline, yycolumn, sym.NAVIGATE);
            }
          // fall through
          case 143: break;
          case 69:
            { return token(yytext(), "OBSTACLE", yyline, yycolumn, sym.OBSTACLE);
            }
          // fall through
          case 144: break;
          case 70:
            { return token(yytext(), "WAYPOINT", yyline, yycolumn, sym.WAYPOINT);
            }
          // fall through
          case 145: break;
          case 71:
            { return token(yytext(), "BROADCAST", yyline, yycolumn, sym.BROADCAST);
            }
          // fall through
          case 146: break;
          case 72:
            { return token(yytext(), "ACCEL", yyline, yycolumn, sym.ACCEL);
            }
          // fall through
          case 147: break;
          case 73:
            { return token(yytext(), "DECEL", yyline, yycolumn, sym.DECEL);
            }
          // fall through
          case 148: break;
          case 74:
            { return token(yytext(), "VEHICLE_ID", yyline, yycolumn, sym.VEHICLE_ID);
            }
          // fall through
          case 149: break;
          case 75:
            { return token(yytext(), "DESTINATION", yyline, yycolumn, sym.DESTINATION);
            }
          // fall through
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
