
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------
import java_cup.runtime.XMLElement;
import java.util.ArrayList;
import java.util.List;
import compilerTools.ErrorLSSL;
import compilerTools.Token;
import compilerTools.ASTNode;
import java_cup.runtime.*;

/**
 * CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
 */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

    public List<ErrorLSSL> errors = new ArrayList<>();

    public final Class getSymbolContainer() {
        return sym.class;
    }

    /**
     * Default constructor.
     */
    @Deprecated
    public Parser() {
        super();
    }

    /**
     * Constructor which sets the default scanner.
     */
    @Deprecated
    public Parser(java_cup.runtime.Scanner s) {
        super(s);
    }

    /**
     * Constructor which sets the default scanner.
     */
    public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {
        super(s, sf);
    }

    /**
     * Production table.
     */
    protected static final short _production_table[][]
            = unpackFromStrings(new String[]{
        "\000\051\000\002\002\004\000\002\002\002\000\002\002"
        + "\005\000\002\002\004\000\002\003\005\000\002\003\003"
        + "\000\002\003\003\000\002\003\003\000\002\003\005\000"
        + "\002\003\005\000\002\007\007\000\002\007\011\000\002"
        + "\010\013\000\002\013\005\000\002\013\005\000\002\013"
        + "\005\000\002\013\005\000\002\013\005\000\002\013\005"
        + "\000\002\013\003\000\002\011\005\000\002\012\002\000"
        + "\002\012\005\000\002\012\004\000\002\014\005\000\002"
        + "\014\003\000\002\014\005\000\002\014\005\000\002\004"
        + "\005\000\002\004\005\000\002\004\003\000\002\005\005"
        + "\000\002\005\005\000\002\005\003\000\002\006\003\000"
        + "\002\006\003\000\002\006\003\000\002\006\006\000\002"
        + "\006\006\000\002\006\005\000\002\006\003"});

    /**
     * Access to production table.
     */
    public short[][] production_table() {
        return _production_table;
    }

    /**
     * Parse-action table.
     */
    protected static final short[][] _action_table
            = unpackFromStrings(new String[]{
        "\000\123\000\030\002\000\003\000\012\000\013\000\014"
        + "\000\015\000\016\000\017\000\020\000\035\000\037\000"
        + "\001\002\000\030\002\010\003\021\012\022\013\006\014"
        + "\024\015\017\016\025\017\023\020\015\035\013\037\005"
        + "\001\002\000\004\020\116\001\002\000\004\020\113\001"
        + "\002\000\034\002\ufffb\003\ufffb\012\ufffb\013\ufffb\014\ufffb"
        + "\015\ufffb\016\ufffb\017\ufffb\020\ufffb\021\ufffb\026\ufffb\035"
        + "\ufffb\037\ufffb\001\002\000\004\002\001\001\002\000\040"
        + "\002\ufffa\003\ufffa\004\032\005\033\012\ufffa\013\ufffa\014"
        + "\ufffa\015\ufffa\016\ufffa\017\ufffa\020\ufffa\021\ufffa\026\ufffa"
        + "\035\ufffa\037\ufffa\001\002\000\034\002\ufffc\003\ufffc\012"
        + "\ufffc\013\ufffc\014\ufffc\015\ufffc\016\ufffc\017\ufffc\020\ufffc"
        + "\021\ufffc\026\ufffc\035\ufffc\037\ufffc\001\002\000\004\020"
        + "\052\001\002\000\032\002\ufffe\003\ufffe\012\ufffe\013\ufffe"
        + "\014\ufffe\015\ufffe\016\ufffe\017\ufffe\020\ufffe\026\051\035"
        + "\ufffe\037\ufffe\001\002\000\020\012\022\013\006\014\024"
        + "\015\017\016\025\017\031\020\015\001\002\000\060\002"
        + "\uffe3\003\uffe3\004\uffe3\005\uffe3\006\035\007\036\012\uffe3"
        + "\013\uffe3\014\uffe3\015\uffe3\016\uffe3\017\uffe3\020\uffe3\021"
        + "\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3\032\uffe3\033\uffe3"
        + "\034\uffe3\035\uffe3\037\uffe3\001\002\000\060\002\uffdf\003"
        + "\uffdf\004\uffdf\005\uffdf\006\uffdf\007\uffdf\012\uffdf\013\uffdf"
        + "\014\uffdf\015\uffdf\016\uffdf\017\uffdf\020\uffdf\021\uffdf\026"
        + "\uffdf\027\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf\034\uffdf"
        + "\035\uffdf\037\uffdf\001\002\000\060\002\uffe0\003\uffe0\004"
        + "\uffe0\005\uffe0\006\uffe0\007\uffe0\012\uffe0\013\uffe0\014\uffe0"
        + "\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021\uffe0\026\uffe0\027"
        + "\uffe0\030\uffe0\031\uffe0\032\uffe0\033\uffe0\034\uffe0\035\uffe0"
        + "\037\uffe0\001\002\000\004\024\045\001\002\000\004\020"
        + "\042\001\002\000\046\002\uffdd\003\uffdd\004\uffdd\005\uffdd"
        + "\006\uffdd\007\uffdd\012\uffdd\013\uffdd\014\uffdd\015\uffdd\016"
        + "\uffdd\017\uffdd\020\uffdd\021\uffdd\024\026\026\uffdd\035\uffdd"
        + "\037\uffdd\001\002\000\060\002\uffd9\003\uffd9\004\uffd9\005"
        + "\uffd9\006\uffd9\007\uffd9\012\uffd9\013\uffd9\014\uffd9\015\uffd9"
        + "\016\uffd9\017\uffd9\020\uffd9\021\uffd9\026\uffd9\027\uffd9\030"
        + "\uffd9\031\uffd9\032\uffd9\033\uffd9\034\uffd9\035\uffd9\037\uffd9"
        + "\001\002\000\060\002\uffde\003\uffde\004\uffde\005\uffde\006"
        + "\uffde\007\uffde\012\uffde\013\uffde\014\uffde\015\uffde\016\uffde"
        + "\017\uffde\020\uffde\021\uffde\026\uffde\027\uffde\030\uffde\031"
        + "\uffde\032\uffde\033\uffde\034\uffde\035\uffde\037\uffde\001\002"
        + "\000\022\003\030\012\022\013\006\014\024\015\017\016"
        + "\025\017\031\020\015\001\002\000\040\002\ufffd\003\ufffd"
        + "\004\032\005\033\012\ufffd\013\ufffd\014\ufffd\015\ufffd\016"
        + "\ufffd\017\ufffd\020\ufffd\021\ufffd\026\ufffd\035\ufffd\037\ufffd"
        + "\001\002\000\034\002\ufff8\003\ufff8\012\ufff8\013\ufff8\014"
        + "\ufff8\015\ufff8\016\ufff8\017\ufff8\020\ufff8\021\ufff8\026\ufff8"
        + "\035\ufff8\037\ufff8\001\002\000\060\002\uffdd\003\uffdd\004"
        + "\uffdd\005\uffdd\006\uffdd\007\uffdd\012\uffdd\013\uffdd\014\uffdd"
        + "\015\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd\026\uffdd\027"
        + "\uffdd\030\uffdd\031\uffdd\032\uffdd\033\uffdd\034\uffdd\035\uffdd"
        + "\037\uffdd\001\002\000\020\012\022\013\006\014\024\015"
        + "\017\016\025\017\031\020\015\001\002\000\020\012\022"
        + "\013\006\014\024\015\017\016\025\017\031\020\015\001"
        + "\002\000\060\002\uffe4\003\uffe4\004\uffe4\005\uffe4\006\035"
        + "\007\036\012\uffe4\013\uffe4\014\uffe4\015\uffe4\016\uffe4\017"
        + "\uffe4\020\uffe4\021\uffe4\026\uffe4\027\uffe4\030\uffe4\031\uffe4"
        + "\032\uffe4\033\uffe4\034\uffe4\035\uffe4\037\uffe4\001\002\000"
        + "\020\012\022\013\006\014\024\015\017\016\025\017\031"
        + "\020\015\001\002\000\020\012\022\013\006\014\024\015"
        + "\017\016\025\017\031\020\015\001\002\000\060\002\uffe1"
        + "\003\uffe1\004\uffe1\005\uffe1\006\uffe1\007\uffe1\012\uffe1\013"
        + "\uffe1\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1"
        + "\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\033\uffe1\034"
        + "\uffe1\035\uffe1\037\uffe1\001\002\000\060\002\uffe2\003\uffe2"
        + "\004\uffe2\005\uffe2\006\uffe2\007\uffe2\012\uffe2\013\uffe2\014"
        + "\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\026\uffe2"
        + "\027\uffe2\030\uffe2\031\uffe2\032\uffe2\033\uffe2\034\uffe2\035"
        + "\uffe2\037\uffe2\001\002\000\060\002\uffe5\003\uffe5\004\uffe5"
        + "\005\uffe5\006\035\007\036\012\uffe5\013\uffe5\014\uffe5\015"
        + "\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\026\uffe5\027\uffe5"
        + "\030\uffe5\031\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5\037"
        + "\uffe5\001\002\000\020\012\022\013\006\014\024\015\017"
        + "\016\025\017\031\020\015\001\002\000\010\004\032\005"
        + "\033\021\044\001\002\000\060\002\uffdc\003\uffdc\004\uffdc"
        + "\005\uffdc\006\uffdc\007\uffdc\012\uffdc\013\uffdc\014\uffdc\015"
        + "\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc\026\uffdc\027\uffdc"
        + "\030\uffdc\031\uffdc\032\uffdc\033\uffdc\034\uffdc\035\uffdc\037"
        + "\uffdc\001\002\000\020\012\022\013\006\014\024\015\017"
        + "\016\025\017\031\020\015\001\002\000\040\002\ufff9\003"
        + "\ufff9\004\032\005\033\012\ufff9\013\ufff9\014\ufff9\015\ufff9"
        + "\016\ufff9\017\ufff9\020\ufff9\021\ufff9\026\ufff9\035\ufff9\037"
        + "\ufff9\001\002\000\010\004\032\005\033\021\050\001\002"
        + "\000\060\002\uffda\003\uffda\004\uffda\005\uffda\006\uffda\007"
        + "\uffda\012\uffda\013\uffda\014\uffda\015\uffda\016\uffda\017\uffda"
        + "\020\uffda\021\uffda\026\uffda\027\uffda\030\uffda\031\uffda\032"
        + "\uffda\033\uffda\034\uffda\035\uffda\037\uffda\001\002\000\030"
        + "\002\uffff\003\uffff\012\uffff\013\uffff\014\uffff\015\uffff\016"
        + "\uffff\017\uffff\020\uffff\035\uffff\037\uffff\001\002\000\020"
        + "\012\022\013\006\014\024\015\017\016\025\017\031\020"
        + "\015\001\002\000\004\021\071\001\002\000\026\004\032"
        + "\005\033\021\uffee\026\uffee\027\057\030\055\031\061\032"
        + "\060\033\056\034\062\001\002\000\020\012\022\013\006"
        + "\014\024\015\017\016\025\017\031\020\015\001\002\000"
        + "\020\012\022\013\006\014\024\015\017\016\025\017\031"
        + "\020\015\001\002\000\020\012\022\013\006\014\024\015"
        + "\017\016\025\017\031\020\015\001\002\000\020\012\022"
        + "\013\006\014\024\015\017\016\025\017\031\020\015\001"
        + "\002\000\020\012\022\013\006\014\024\015\017\016\025"
        + "\017\031\020\015\001\002\000\020\012\022\013\006\014"
        + "\024\015\017\016\025\017\031\020\015\001\002\000\012"
        + "\004\032\005\033\021\uffef\026\uffef\001\002\000\012\004"
        + "\032\005\033\021\ufff2\026\ufff2\001\002\000\012\004\032"
        + "\005\033\021\ufff1\026\ufff1\001\002\000\012\004\032\005"
        + "\033\021\ufff4\026\ufff4\001\002\000\012\004\032\005\033"
        + "\021\ufff0\026\ufff0\001\002\000\012\004\032\005\033\021"
        + "\ufff3\026\ufff3\001\002\000\004\022\072\001\002\000\024"
        + "\003\uffec\012\uffec\013\uffec\014\uffec\015\uffec\016\uffec\017"
        + "\uffec\020\uffec\023\uffec\001\002\000\036\002\ufff7\003\ufff7"
        + "\012\ufff7\013\ufff7\014\ufff7\015\ufff7\016\ufff7\017\ufff7\020"
        + "\ufff7\021\ufff7\026\ufff7\035\ufff7\036\074\037\ufff7\001\002"
        + "\000\004\022\072\001\002\000\034\002\ufff6\003\ufff6\012"
        + "\ufff6\013\ufff6\014\ufff6\015\ufff6\016\ufff6\017\ufff6\020\ufff6"
        + "\021\ufff6\026\ufff6\035\ufff6\037\ufff6\001\002\000\024\003"
        + "\101\012\022\013\006\014\024\015\017\016\025\017\102"
        + "\020\015\023\104\001\002\000\010\004\032\005\033\026"
        + "\uffe8\001\002\000\004\026\112\001\002\000\004\024\110"
        + "\001\002\000\016\004\uffdd\005\uffdd\006\uffdd\007\uffdd\024"
        + "\105\026\uffdd\001\002\000\024\003\uffea\012\uffea\013\uffea"
        + "\014\uffea\015\uffea\016\uffea\017\uffea\020\uffea\023\uffea\001"
        + "\002\000\036\002\uffed\003\uffed\012\uffed\013\uffed\014\uffed"
        + "\015\uffed\016\uffed\017\uffed\020\uffed\021\uffed\026\uffed\035"
        + "\uffed\036\uffed\037\uffed\001\002\000\022\003\107\012\022"
        + "\013\006\014\024\015\017\016\025\017\031\020\015\001"
        + "\002\000\010\004\032\005\033\026\uffe9\001\002\000\004"
        + "\026\uffe6\001\002\000\020\012\022\013\006\014\024\015"
        + "\017\016\025\017\031\020\015\001\002\000\010\004\032"
        + "\005\033\026\uffe7\001\002\000\024\003\uffeb\012\uffeb\013"
        + "\uffeb\014\uffeb\015\uffeb\016\uffeb\017\uffeb\020\uffeb\023\uffeb"
        + "\001\002\000\020\012\022\013\006\014\024\015\017\016"
        + "\025\017\031\020\015\001\002\000\010\004\032\005\033"
        + "\021\115\001\002\000\060\002\uffdb\003\uffdb\004\uffdb\005"
        + "\uffdb\006\uffdb\007\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb"
        + "\016\uffdb\017\uffdb\020\uffdb\021\uffdb\026\uffdb\027\uffdb\030"
        + "\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035\uffdb\037\uffdb"
        + "\001\002\000\026\003\021\012\022\013\006\014\024\015"
        + "\017\016\025\017\023\020\015\035\013\037\005\001\002"
        + "\000\004\026\120\001\002\000\020\012\022\013\006\014"
        + "\024\015\017\016\025\017\031\020\015\001\002\000\004"
        + "\026\122\001\002\000\026\003\021\012\022\013\006\014"
        + "\024\015\017\016\025\017\023\020\015\035\013\037\005"
        + "\001\002\000\004\021\124\001\002\000\004\022\072\001"
        + "\002\000\034\002\ufff5\003\ufff5\012\ufff5\013\ufff5\014\ufff5"
        + "\015\ufff5\016\ufff5\017\ufff5\020\ufff5\021\ufff5\026\ufff5\035"
        + "\ufff5\037\ufff5\001\002"});

    /**
     * Access to parse-action table.
     */
    public short[][] action_table() {
        return _action_table;
    }

    /** <code>reduce_goto</code> table.
     */
    protected static final short[][] _reduce_table
            = unpackFromStrings(new String[]{
        "\000\123\000\004\002\003\001\001\000\016\003\013\004"
        + "\010\005\015\006\017\007\011\010\006\001\001\000\002"
        + "\001\001\000\002\001\001\000\002\001\001\000\002\001"
        + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
        + "\000\002\001\001\000\010\004\046\005\015\006\017\001"
        + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
        + "\000\002\001\001\000\002\001\001\000\002\001\001\000"
        + "\002\001\001\000\002\001\001\000\010\004\026\005\015"
        + "\006\017\001\001\000\002\001\001\000\002\001\001\000"
        + "\002\001\001\000\006\005\040\006\017\001\001\000\006"
        + "\005\033\006\017\001\001\000\002\001\001\000\004\006"
        + "\037\001\001\000\004\006\036\001\001\000\002\001\001"
        + "\000\002\001\001\000\002\001\001\000\010\004\042\005"
        + "\015\006\017\001\001\000\002\001\001\000\002\001\001"
        + "\000\010\004\045\005\015\006\017\001\001\000\002\001"
        + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
        + "\000\012\004\053\005\015\006\017\013\052\001\001\000"
        + "\002\001\001\000\002\001\001\000\010\004\067\005\015"
        + "\006\017\001\001\000\010\004\066\005\015\006\017\001"
        + "\001\000\010\004\065\005\015\006\017\001\001\000\010"
        + "\004\064\005\015\006\017\001\001\000\010\004\063\005"
        + "\015\006\017\001\001\000\010\004\062\005\015\006\017"
        + "\001\001\000\002\001\001\000\002\001\001\000\002\001"
        + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
        + "\000\004\011\072\001\001\000\004\012\075\001\001\000"
        + "\002\001\001\000\004\011\074\001\001\000\002\001\001"
        + "\000\014\004\076\005\015\006\017\014\077\015\102\001"
        + "\001\000\002\001\001\000\002\001\001\000\002\001\001"
        + "\000\002\001\001\000\002\001\001\000\002\001\001\000"
        + "\010\004\105\005\015\006\017\001\001\000\002\001\001"
        + "\000\002\001\001\000\010\004\110\005\015\006\017\001"
        + "\001\000\002\001\001\000\002\001\001\000\010\004\113"
        + "\005\015\006\017\001\001\000\002\001\001\000\002\001"
        + "\001\000\016\003\116\004\010\005\015\006\017\007\011"
        + "\010\006\001\001\000\002\001\001\000\012\004\053\005"
        + "\015\006\017\013\120\001\001\000\002\001\001\000\016"
        + "\003\122\004\010\005\015\006\017\007\011\010\006\001"
        + "\001\000\002\001\001\000\004\011\124\001\001\000\002"
        + "\001\001"});

    /**
     * Access to <code>reduce_goto</code> table.
     */
    public short[][] reduce_table() {
        return _reduce_table;
    }

    /**
     * Instance of action encapsulation class.
     */
    protected CUP$Parser$actions action_obj;

    /**
     * Action encapsulation object initializer.
     */
    protected void init_actions() {
        action_obj = new CUP$Parser$actions(this);
    }

    /**
     * Invoke a user supplied parse action.
     */
    public java_cup.runtime.Symbol do_action(
            int act_num,
            java_cup.runtime.lr_parser parser,
            java.util.Stack stack,
            int top)
            throws java.lang.Exception {
        /* call code in generated class */
        return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
    }

    /**
     * Indicates start state.
     */
    public int start_state() {
        return 0;
    }

    /**
     * Indicates start production.
     */
    public int start_production() {
        return 0;
    }

    /** <code>EOF</code> Symbol index.
     */
    public int EOF_sym() {
        return 0;
    }

    /** <code>error</code> Symbol index.
     */
    public int error_sym() {
        return 1;
    }

    /**
     * Cup generated class to encapsulate user supplied action code.
     */
    @SuppressWarnings({"rawtypes", "unchecked", "unused"})
    class CUP$Parser$actions {

        private final Parser parser;

        /**
         * Constructor
         */
        CUP$Parser$actions(Parser parser) {
            this.parser = parser;
        }

        /**
         * Method 0 with the actual generated action code for actions 0 to 300.
         */
        public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
                int CUP$Parser$act_num,
                java_cup.runtime.lr_parser CUP$Parser$parser,
                java.util.Stack CUP$Parser$stack,
                int CUP$Parser$top)
                throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$Parser$result;

            /* select the action based on the action number */
            switch (CUP$Parser$act_num) {
                /*. . . . . . . . . . . . . . . . . . . .*/
                case 0: // $START ::= Program EOF 
                {
                    Object RESULT = null;
                    int start_valleft = ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)).left;
                    int start_valright = ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)).right;
                    ASTNode start_val = (ASTNode) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)).value;
                    RESULT = start_val;
                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START", 0, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                /* ACCEPT */
                CUP$Parser$parser.done_parsing();
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 1: // Program ::= 
                {
                    ASTNode RESULT = null;
                    RESULT = new ASTNode("Program");
                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program", 0, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 2: // Program ::= Program Statement SEMICOLON 
                {
                    ASTNode RESULT = null;

                    Symbol prog = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol stmt = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 1);
                    ASTNode node = (ASTNode) prog.value;
                    node.addChild((ASTNode) stmt.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program", 0, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 3: // Program ::= Program Statement 
                {
                    ASTNode RESULT = null;

                    Symbol prog = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 1);
                    Symbol stmt = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = (ASTNode) prog.value;
                    node.addChild((ASTNode) stmt.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program", 0, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 4: // Statement ::= IDENTIFIER ASSIGNMENT Expression 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    Token idToken = (Token) sym1.value;
                    ASTNode assign = new ASTNode("Assign");
                    assign.addChild(new ASTNode("ID: " + idToken.getLexeme()));
                    assign.addChild((ASTNode) sym3.value);
                    RESULT = assign;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement", 1, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 5: // Statement ::= IfStatement 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    RESULT = (ASTNode) sym1.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement", 1, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 6: // Statement ::= ForStatement 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    RESULT = (ASTNode) sym1.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement", 1, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 7: // Statement ::= Expression 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    RESULT = (ASTNode) sym1.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement", 1, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 8: // Statement ::= error ASSIGNMENT Expression 
                {
                    ASTNode RESULT = null;

                    errors.add(new ErrorLSSL(0, 0, "Error sintáctico: falta identificador antes de '='."));
                    RESULT = new ASTNode("Error");

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement", 1, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 9: // Statement ::= IDENTIFIER ASSIGNMENT error 
                {
                    ASTNode RESULT = null;

                    errors.add(new ErrorLSSL(0, 0, "Error sintáctico: falta expresión después de '='."));
                    RESULT = new ASTNode("Error");

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Statement", 1, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 10: // IfStatement ::= IF LEFT_PAREN RelationalExpression RIGHT_PAREN Block 
                {
                    ASTNode RESULT = null;

                    Symbol cond = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol block = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("If");
                    node.addChild((ASTNode) cond.value);
                    node.addChild((ASTNode) block.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("IfStatement", 5, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 4)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 11: // IfStatement ::= IF LEFT_PAREN RelationalExpression RIGHT_PAREN Block ELSE Block 
                {
                    ASTNode RESULT = null;

                    Symbol cond = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 4);
                    Symbol ifBlock = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol elseBlock = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("IfElse");
                    node.addChild((ASTNode) cond.value);
                    node.addChild((ASTNode) ifBlock.value);
                    node.addChild((ASTNode) elseBlock.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("IfStatement", 5, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 6)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 12: // ForStatement ::= FOR LEFT_PAREN Statement SEMICOLON RelationalExpression SEMICOLON Statement RIGHT_PAREN Block 
                {
                    ASTNode RESULT = null;

                    Symbol init = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 6);
                    Symbol cond = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 4);
                    Symbol update = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol block = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("For");
                    node.addChild((ASTNode) init.value);
                    node.addChild((ASTNode) cond.value);
                    node.addChild((ASTNode) update.value);
                    node.addChild((ASTNode) block.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("ForStatement", 6, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 8)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 13: // RelationalExpression ::= Expression GT Expression 
                {
                    ASTNode RESULT = null;

                    ASTNode node = new ASTNode(">");
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2)).value);
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 14: // RelationalExpression ::= Expression LT Expression 
                {
                    ASTNode RESULT = null;

                    ASTNode node = new ASTNode("<");
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2)).value);
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 15: // RelationalExpression ::= Expression GE Expression 
                {
                    ASTNode RESULT = null;

                    ASTNode node = new ASTNode(">=");
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2)).value);
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 16: // RelationalExpression ::= Expression LE Expression 
                {
                    ASTNode RESULT = null;

                    ASTNode node = new ASTNode("<=");
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2)).value);
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 17: // RelationalExpression ::= Expression EQ Expression 
                {
                    ASTNode RESULT = null;

                    ASTNode node = new ASTNode("==");
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2)).value);
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 18: // RelationalExpression ::= Expression NE Expression 
                {
                    ASTNode RESULT = null;

                    ASTNode node = new ASTNode("!=");
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2)).value);
                    node.addChild((ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 19: // RelationalExpression ::= Expression 
                {
                    ASTNode RESULT = null;

                    RESULT = (ASTNode) ((Symbol) ((java.util.Stack) CUP$Parser$stack).peek()).value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("RelationalExpression", 9, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 20: // Block ::= LBRACE StatementList RBRACE 
                {
                    ASTNode RESULT = null;

                    Symbol stmts = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 1);
                    ASTNode node = new ASTNode("Block");
                    node.addChild((ASTNode) stmts.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Block", 7, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 21: // StatementList ::= 
                {
                    ASTNode RESULT = null;
                    RESULT = new ASTNode("Statements");
                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("StatementList", 8, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 22: // StatementList ::= StatementList SimpleStatement SEMICOLON 
                {
                    ASTNode RESULT = null;

                    Symbol stmts = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol stmt = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 1);
                    ASTNode node = (ASTNode) stmts.value;
                    node.addChild((ASTNode) stmt.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("StatementList", 8, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 23: // StatementList ::= StatementList ControlStatement 
                {
                    ASTNode RESULT = null;

                    Symbol stmts = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 1);
                    Symbol stmt = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = (ASTNode) stmts.value;
                    node.addChild((ASTNode) stmt.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("StatementList", 8, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 24: // SimpleStatement ::= IDENTIFIER ASSIGNMENT Expression 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    Token idToken = (Token) sym1.value;
                    ASTNode assign = new ASTNode("Assign");
                    assign.addChild(new ASTNode("ID: " + idToken.getLexeme()));
                    assign.addChild((ASTNode) sym3.value);
                    RESULT = assign;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("SimpleStatement", 10, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 25: // SimpleStatement ::= Expression 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    RESULT = (ASTNode) sym1.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("SimpleStatement", 10, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 26: // SimpleStatement ::= error ASSIGNMENT Expression 
                {
                    ASTNode RESULT = null;

                    errors.add(new ErrorLSSL(0, 0, "Error sintáctico: falta identificador antes de '='."));
                    RESULT = new ASTNode("Error");

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("SimpleStatement", 10, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 27: // SimpleStatement ::= IDENTIFIER ASSIGNMENT error 
                {
                    ASTNode RESULT = null;

                    errors.add(new ErrorLSSL(0, 0, "Error sintáctico: falta expresión después de '='."));
                    RESULT = new ASTNode("Error");

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("SimpleStatement", 10, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 28: // Expression ::= Expression PLUS Term 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("+");
                    node.addChild((ASTNode) sym1.value);
                    node.addChild((ASTNode) sym3.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression", 2, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 29: // Expression ::= Expression MINUS Term 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("-");
                    node.addChild((ASTNode) sym1.value);
                    node.addChild((ASTNode) sym3.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression", 2, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 30: // Expression ::= Term 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    RESULT = (ASTNode) sym1.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expression", 2, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 31: // Term ::= Term MUL Factor 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("*");
                    node.addChild((ASTNode) sym1.value);
                    node.addChild((ASTNode) sym3.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Term", 3, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 32: // Term ::= Term DIV Factor 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    ASTNode node = new ASTNode("/");
                    node.addChild((ASTNode) sym1.value);
                    node.addChild((ASTNode) sym3.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Term", 3, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 33: // Term ::= Factor 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    RESULT = (ASTNode) sym1.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Term", 3, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 34: // Factor ::= FLOAT_LITERAL 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    Token tok = (Token) sym1.value;
                    RESULT = new ASTNode("Float: " + tok.getLexeme());

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 35: // Factor ::= INTEGER_LITERAL 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    Token tok = (Token) sym1.value;
                    RESULT = new ASTNode("Int: " + tok.getLexeme());

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 36: // Factor ::= IDENTIFIER 
                {
                    ASTNode RESULT = null;

                    Symbol sym1 = (Symbol) ((java.util.Stack) CUP$Parser$stack).peek();
                    Token tok = (Token) sym1.value;
                    RESULT = new ASTNode("ID: " + tok.getLexeme());

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 37: // Factor ::= SQRT LEFT_PAREN Expression RIGHT_PAREN 
                {
                    ASTNode RESULT = null;

                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    ASTNode node = new ASTNode("SQRT");
                    node.addChild((ASTNode) sym3.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 3)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 38: // Factor ::= SIN LEFT_PAREN Expression RIGHT_PAREN 
                {
                    ASTNode RESULT = null;

                    Symbol sym3 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 2);
                    ASTNode node = new ASTNode("SIN");
                    node.addChild((ASTNode) sym3.value);
                    RESULT = node;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 3)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 39: // Factor ::= LEFT_PAREN Expression RIGHT_PAREN 
                {
                    ASTNode RESULT = null;

                    Symbol sym2 = (Symbol) ((java.util.Stack) CUP$Parser$stack).elementAt(CUP$Parser$top - 1);
                    RESULT = (ASTNode) sym2.value;

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 2)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 40: // Factor ::= PI 
                {
                    ASTNode RESULT = null;

                    RESULT = new ASTNode("PI");

                    CUP$Parser$result = parser.getSymbolFactory().newSymbol("Factor", 4, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /* . . . . . .*/
                default:
                    throw new Exception(
                            "Invalid action number " + CUP$Parser$act_num + "found in internal parse table");

            }
        }

        /* end of method */

        /**
         * Method splitting the generated action code into several parts.
         */
        public final java_cup.runtime.Symbol CUP$Parser$do_action(
                int CUP$Parser$act_num,
                java_cup.runtime.lr_parser CUP$Parser$parser,
                java.util.Stack CUP$Parser$stack,
                int CUP$Parser$top)
                throws java.lang.Exception {
            return CUP$Parser$do_action_part00000000(
                    CUP$Parser$act_num,
                    CUP$Parser$parser,
                    CUP$Parser$stack,
                    CUP$Parser$top);
        }
    }

}
